# Generated by Django 2.0.3 on 2018-10-06 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_auto_20181004_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
