# Generated by Django 2.0.3 on 2018-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_asignacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grado',
            field=models.IntegerField(),
        ),
    ]
