# Generated by Django 2.0.3 on 2018-10-07 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_asignacion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fechaFinal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='avatar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
