# Generated by Django 2.0.3 on 2018-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
