# Generated by Django 2.0.3 on 2018-10-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0010_auto_20181013_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='detalle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fechaFinal',
            field=models.DateField(null=True),
        ),
    ]
